sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: abcd12301016
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: bala
    access-key-secret: bala
    bucket-name: sky-takeout-ganster
  wechat:
    secret: c9f2d2eb8a5c12480925e3103724d3b1
    appid: wxe7725d10918b4d1b
  redis:
    host: localhost
    port: 6379
    password:
    datebase: 10
  baidu:
    ak: sN1HGO2HXZMKxyA30vPLCym9dGWBcpAc
  shop:
    address: 北京市海淀区上地十街10号